- attribute_name: stylometrix_metrics.grammatical_forms.G_PRO_REL
  type: bidirectional
- attribute_name: combination_features.common_long_word_ratio
  type: bidirectional
- attribute_name: stylometrix_metrics.grammatical_forms.G_ADP
  type: bidirectional
- attribute_name: combination_features.partial_attribute_statistics.perplexity_base.average
  type: bidirectional
- attribute_name: combination_features.partial_attribute_statistics.perplexity_base_normalized.average
  type: bidirectional
- attribute_name: combination_features.partial_attribute_statistics.perplexity.average
  type: bidirectional
- attribute_name: stylometrix_metrics.inflection.IN_PRO_1NOM
  type: bidirectional
- attribute_name: stylometrix_metrics.syntactic.SY_S_NOM
  type: bidirectional
- attribute_name: stylometrix_metrics.lexical.L_CONT_A
  type: bidirectional
- attribute_name: combination_features.common_rare_word_ratio
  type: bidirectional
- attribute_name: stylometrix_metrics.lexical.L_TCCT1
  type: bidirectional
- attribute_name: perplexity_base
  type: bidirectional
- attribute_name: stylometrix_metrics.lexical.L_CONT_T
  type: bidirectional
- attribute_name: combination_features.partial_attribute_statistics.number_of_errors.average
  type: bidirectional
- attribute_name: number_of_errors
  type: bidirectional
- attribute_name: stylometrix_metrics.inflection.IN_V_ACT
  type: bidirectional
- attribute_name: combination_features.partial_attribute_statistics.standard_deviation_sentence_char_length.average
  type: bidirectional
- attribute_name: combination_features.partial_attribute_statistics.variance_sentence_char_length.average
  type: bidirectional