from typing import Optional

from pydantic import BaseModel

class StyloMetrixMetrics(BaseModel):
    text:Optional[str] = None # Original text
    G_N:Optional[float] = None # Nouns
    G_V:Optional[float] = None # Verbs
    G_ADJ:Optional[float] = None # Adjectives
    G_ADJ_CP:Optional[float] = None # Compound adjectives
    G_ADV:Optional[float] = None # Adverbs
    G_PRO:Optional[float] = None # Pronouns
    G_PRO_PRS:Optional[float] = None # Personal pronouns
    G_PRO_REL:Optional[float] = None # Relative pronouns
    G_PRO_DEM:Optional[float] = None # Demonstrative pronouns
    G_PRO_INT:Optional[float] = None # Interrogative pronouns
    G_PRO_IND:Optional[float] = None # Indefinite pronouns
    G_PRO_TOT:Optional[float] = None # Total pronouns
    G_PRO_NEG:Optional[float] = None # Negative pronouns
    G_PRO_POS:Optional[float] = None # Possessive pronouns
    G_NUM:Optional[float] = None # Numerals
    G_CNUM:Optional[float] = None # Collective numerals
    G_PART:Optional[float] = None # Particles
    G_ADP:Optional[float] = None # Adpositions
    G_INTJ:Optional[float] = None # Interjections
    G_SYM:Optional[float] = None # Symbols
    G_ABBR:Optional[float] = None # Abbreviations
    G_CONJ:Optional[float] = None # Conjunctions
    G_CCONJ:Optional[float] = None # Coordinating conjunctions
    G_SCONJ:Optional[float] = None # Subordinating conjunctions
    G_OTHER:Optional[float] = None # Other parts of speech
    PUNCT_TOTAL:Optional[float] = None # Total punctuation
    PUNCT_BI_NOUN:Optional[float] = None # Punctuation following a noun
    PUNCT_BI_VERB:Optional[float] = None # Punctuation following a verb
    SY_FMWE:Optional[float] = None # Flat multiword expressions
    SY_APPM:Optional[float] = None # Appositional modifiers
    SY_S_DE:Optional[float] = None # Words in declarative sentences
    SY_S_EX:Optional[float] = None # Words in exclamatory sentences
    SY_S_IN:Optional[float] = None # Words in interrogative sentences
    SY_S_NEG:Optional[float] = None # Words in negative sentences
    SY_S_ELL:Optional[float] = None # Words in ellipsis-ending sentences
    SY_S_VOC:Optional[float] = None # Words in sentences with a noun in the vocative case
    SY_S_NOM:Optional[float] = None # Words in nominal sentences
    SY_S_INF:Optional[float] = None # Words in infinitive-only sentences without finite verbs
    SY_NPRED:Optional[float] = None # Words in nominal predicates
    SY_MOD:Optional[float] = None # Words within modifiers
    SY_NPHR:Optional[float] = None # Words in nominal phrases
    SY_INV_OBJ:Optional[float] = None # OVS word order
    SY_INV_EPI:Optional[float] = None # Inverted epithet
    SY_INIT:Optional[float] = None # Words being the initial token in a sentence
    SY_QUOT:Optional[float] = None # Words in quotation marks
    SY_SIMILE_NP:Optional[float] = None # Similes (noun/pronoun)
    SY_SIMILE_ADJ:Optional[float] = None # Similes (adjective)
    GR_UPPER:Optional[float] = None # Capital letters
    GR_EMOJI:Optional[float] = None # Emojis
    GR_EMOT:Optional[float] = None # Emoticons
    GR_LENNY:Optional[float] = None # Lenny faces
    GR_MENTION:Optional[float] = None # Direct mentions with @
    GR_HASH:Optional[float] = None # Hashtags
    GR_LINK:Optional[float] = None # Hyperlinks
    IN_ADJ_POS:Optional[float] = None # Adjectives in positive degree
    IN_ADJ_COM:Optional[float] = None # Adjectives in comparative degree
    IN_ADJ_SUP:Optional[float] = None # Adjectives in superlative degree
    IN_ADV_POS:Optional[float] = None # Adverbs in positive degree
    IN_ADV_COM:Optional[float] = None # Adverbs in comparative degree
    IN_ADV_SUP:Optional[float] = None # Adverbs in superlative degree
    IN_N_1NOM:Optional[float] = None # Nouns in the nominative case
    IN_N_2GEN:Optional[float] = None # Nouns in the genitive case
    IN_N_3DAT:Optional[float] = None # Nouns in the dative case
    IN_N_4ACC:Optional[float] = None # Nouns in the accusative case
    IN_N_5INS:Optional[float] = None # Nouns in the instrumental case
    IN_N_6LOC:Optional[float] = None # Nouns in the locative case
    IN_N_7VOC:Optional[float] = None # Nouns in the vocative case
    IN_N_SG:Optional[float] = None # Singular nouns
    IN_N_PL:Optional[float] = None # Plural nouns
    IN_N_MS:Optional[float] = None # Masculine singular nouns
    IN_N_MP:Optional[float] = None # Nouns in masculine personal gender (plural)
    IN_N_FS:Optional[float] = None # Feminine singular nouns
    IN_N_NMP:Optional[float] = None # Nouns in non-masculine personal gender (plural)
    IN_N_NS:Optional[float] = None # Singular neutral nouns
    IN_PRO_1NOM:Optional[float] = None # Pronouns in the nominative case
    IN_PRO_2GEN:Optional[float] = None # Pronouns in the genitive case
    IN_PRO_3DAT:Optional[float] = None # Pronouns in the dative case
    IN_PRO_4ACC:Optional[float] = None # Pronouns in the accusative case
    IN_PRO_5INS:Optional[float] = None # Pronouns in the instrumental case
    IN_PRO_6LOC:Optional[float] = None # Pronouns in the locative case
    IN_PRO_7VOC:Optional[float] = None # Pronouns in the vocative case
    IN_PRO_1S:Optional[float] = None # First person singular pronouns
    IN_PRO_2S:Optional[float] = None # Second person singular pronouns
    IN_PRO_3S:Optional[float] = None # Third person singular pronouns
    IN_PRO_1P:Optional[float] = None # First person plural pronouns
    IN_PRO_2P:Optional[float] = None # Second person plural pronouns
    IN_PRO_3P:Optional[float] = None # Third person plural pronouns
    IN_V_1S:Optional[float] = None # Verbs in first person singular
    IN_V_2S:Optional[float] = None # Verbs in second person singular
    IN_V_3S:Optional[float] = None # Verbs in third person singular
    IN_V_1P:Optional[float] = None # Verbs in first person plural
    IN_V_2P:Optional[float] = None # Verbs in second person plural
    IN_V_3P:Optional[float] = None # Verbs in third person singular
    IN_V_FIN:Optional[float] = None # Finite verbs
    IN_V_INF:Optional[float] = None # Infinitive verbs
    IN_V_QUASI:Optional[float] = None # Quasi-verbs
    IN_V_IMPERS:Optional[float] = None # Impersonal verb forms
    IN_V_IMPERS_PERF:Optional[float] = None # Impersonal verb forms in perfective aspect
    IN_V_IMPERS_IMPERF:Optional[float] = None # Impersonal verb forms in imperfective aspect
    IN_V_MOD:Optional[float] = None # Modal verbs ("should")
    IN_V_PACT:Optional[float] = None # Active adjectival participles
    IN_V_PPAS:Optional[float] = None # Passive adjectival participles
    IN_V_PPAS_PERF:Optional[float] = None # Passive adjectival participles in perfective aspect
    IN_V_PPAS_IMPERF:Optional[float] = None # Passive adjectival participles in imperfective aspect
    IN_V_PCON:Optional[float] = None # Present adverbial participles
    IN_V_PANT:Optional[float] = None # Perfect adverbial participles
    IN_V_PERF:Optional[float] = None # Verbs in perfect aspect
    IN_V_IMPERF:Optional[float] = None # Verbs in imperfect aspect
    IN_V_ACT:Optional[float] = None # Verbs in active voice
    IN_V_PASS:Optional[float] = None # Verbs in passive voice
    IN_V_GER:Optional[float] = None # Gerunds
    IN_V_PRES:Optional[float] = None # Verbs in present tense
    IN_V_PAST:Optional[float] = None # Verbs in past tense
    IN_V_FUTS:Optional[float] = None # Verbs in simple future tense
    IN_V_FUTC:Optional[float] = None # Verbs in compound future tense
    IN_V_FUT:Optional[float] = None # Verbs in future tense
    IN_V_IMP:Optional[float] = None # Verbs in imperative mood
    IN_V_COND:Optional[float] = None # Verbs in conditional mood
    L_NAME:Optional[float] = None # Proper names
    L_NAME_M:Optional[float] = None # Masculine proper names
    L_NAME_F:Optional[float] = None # Feminine proper names
    L_NAME_ENT:Optional[float] = None # Named entities
    L_PLACEN_GEOG:Optional[float] = None # Place and geographical names
    L_PERSN:Optional[float] = None # Person names
    L_PERSN_M:Optional[float] = None # Masculine person names
    L_PERSN_F:Optional[float] = None # Feminine person names
    L_ORGN:Optional[float] = None # Organization names
    L_ETHN:Optional[float] = None # Ethonyms and demonyms
    L_GEOG_ADJ:Optional[float] = None # Adjectives derived from geographical names
    L_DATE:Optional[float] = None # Dates
    L_VULG:Optional[float] = None # Vulgarisms
    L_INTENSIF:Optional[float] = None # Degree modifiers of Greek origin
    L_ERROR:Optional[float] = None # Common linguistic errors
    L_ADVPHR:Optional[float] = None # Adverbial phrases
    L_ADV_TEMP:Optional[float] = None # Adverbs of time
    L_ADV_DUR:Optional[float] = None # Adverbs of duration
    L_ADV_FREQ:Optional[float] = None # Adverbs of frequency
    L_SYL_G1:Optional[float] = None # One-syllable words
    L_SYL_G2:Optional[float] = None # Two-syllables words
    L_SYL_G3:Optional[float] = None # Three-syllables words
    L_SYL_G4:Optional[float] = None # Words formed of 4 or more syllables
    L_TTR_IA:Optional[float] = None # Type-token ratio for non-lemmatized tokens
    L_TTR_LA:Optional[float] = None # Type-token ratio for lemmatized tokens
    L_CONT_A:Optional[float] = None # Incidence of content words
    L_CONT_T:Optional[float] = None # Content words types
    L_CONT_L:Optional[float] = None # Content words lemma types
    L_FUNC_A:Optional[float] = None # Incidence of function words
    L_FUNC_T:Optional[float] = None # Function words types
    L_FUNC_L:Optional[float] = None # Function words lemma types
    L_STOP:Optional[float] = None # Incidence of stop words
    L_TCCT1:Optional[float] = None # Tokens covering 1% of most common types
    L_TCCT5:Optional[float] = None # Tokens covering 5% of most common types
    PS_M_POSa:Optional[float] = None # Words having more than mean positivity
    PS_M_POSb:Optional[float] = None # Words having less than mean positivity
    PS_M_NEGa:Optional[float] = None # Words having more than mean negativity
    PS_M_NEGb:Optional[float] = None # Words having less than mean negativity
    PS_M_REFa:Optional[float] = None # Words having more than mean reflectiveness
    PS_M_REFb:Optional[float] = None # Words having less than mean reflectiveness
    PS_M_AUTa:Optional[float] = None # Words having more than mean automaticity
    PS_M_AUTb:Optional[float] = None # Words having less than mean automaticity
    PS_M_AROa:Optional[float] = None # Words having more than mean arousal
    PS_M_AROb:Optional[float] = None # Words having less than mean arousal
    PS_M_SIGa:Optional[float] = None # Words having more than mean significance
    PS_M_SIGb:Optional[float] = None # Words having less than mean significance
    DESC_ADJ:Optional[float] = None # Adjectival description of qualities
    DESC_ADV:Optional[float] = None # Adverbial description of qualities
    DESC_APOS_ADJ:Optional[float] = None # Descriptive apostrophe with an adjective
    DESC_APOS_NPHR:Optional[float] = None # Descriptive apostrophe with a nominal phrase
    DESC_APOS_VERB:Optional[float] = None # Descriptive apostrophe containing a verb
    DESC_ADV_ADJ:Optional[float] = None # Adverbs followed by adjectives
    DESC_ADV_ADV:Optional[float] = None # Adverb pairs incidence
    DESC_PRON_VOC:Optional[float] = None # Personal pronoun followed by a noun in the vocative case